language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        snaps:
          - name: powershell
            confinement: classic
          - name: powershell-preview
            confinement: classic
    - os: osx
      addons:
        homebrew:
          packages:
          - powershell
          update: true
  fast_finish: true
script:
  - pwsh -f build.ps1