language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod xenial main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: osx
      addons:
        homebrew:
          packages:
          - powershell
  fast_finish: true
script:
  - pwsh -f build.ps1