language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: osx
      addons:
        homebrew:
          packages:
          - powershell
  fast_finish: true
script:
  - pwsh -f build.ps1