language: generic

matrix:
  include:
    - os: linux
      dist: cosmic
      sudo: false
      addons:
        snaps:
          - name: powershell
            confinement: classic
          - name: powershell-preview
            confinement: classic
    - os: osx
      addons:
        homebrew:
          casks:
            - powershell
            - powershell-preview
  fast_finish: true
script:
  - pwsh -f build.ps1