language: generic

matrix:
  include:
    - os: linux
      dist: cosmic
      sudo: false
      addons:
        snaps:
          - powershell
            confinement: classic
          - powershell-preview
            confinement: classic
    - os: osx
      addons:
        homebrew:
          packages:
          - powershell
  fast_finish: true
script:
  - pwsh -f build.ps1