# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

strategy:
  maxParallel: 10
  matrix:
    windows-latest-powershell:
      os: windows-latest
      psversion: powershell
    windows-latest-pwsh:
      os: windows-latest
      psversion: pwsh
    ubuntu-latest-pwsh:
      os: ubuntu-latest
      psversion: pwsh
    macOS-latest-pwsh:
      os: macOS-latest
      psversion: pwsh
    vs2017-win2016-powershell:
      os: vs2017-win2016
      psversion: powershell
    vs2017-win2016-pwsh:
      os: vs2017-win2016
      psversion: pwsh
pool:
  vmImage: $(os)
steps:
- script: "$(psversion) -noninteractive -noprofile -f build.ps1"
  displayName: 'Build and Test Powershell Module'

- task: PublishTestResults@2
  displayName: 'Capture Pester Test Result'
  inputs:
    testRunner: 'NUnit'
    testResultsFiles: '**/*TestResults*.xml'
    testRunTitle: 'Pester $(os)-$(psversion)'

# - task: PublishCodeCoverageResults@2
#   displayName: 'Capture Pester Code Coverage Result'
#   inputs:
#     summaryFileLocation: '**/*CodeCoverage*.xml'
    #failIfCoverageEmpty: false # Optional


- task: PublishPipelineArtifact@1
  displayName: 'Capture Powershell Module Zip as Artifact'
  inputs:
    artifactName: 'PSModule Zip $(os)-$(psversion)'
    targetpath: '$(Build.SourcesDirectory)/BuildOutput/*.zip'

- task: PublishPipelineArtifact@1
  displayName: 'Capture Powershell Module NuGet Package as Artifact'
  inputs:
    artifactName: 'PSModule Nupkg $(os)-$(psversion)'
    targetpath: '$(Build.SourcesDirectory)/BuildOutput/*.nupkg'