parameters:
  jobs: []
  os:
    - 'windows-latest'
    - 'ubuntu-latest'
    - 'macos-latest'
  psversion:
    - 'powershell'
    - 'pwsh'

jobs:
- job: PSBuild
  strategy:
    maxParallel: 10
    matrix:
      Windows-pwsh:
        os: 'windows-latest'
        #${{ format('{0}-{1}', psversion, os) }}:
        #     ${{ each os in parameters.os }}:
  #   #         ${{ each psversion in parameters.psversion }}:
  #   #
  pool:
    vmImage: $(os)
  steps:
  - powershell: .\build.ps1
    displayName: "Powershell Module $(os) $(psversion)"