# https://aka.ms/yaml
parameters:
  vmImage: 'ubuntu-18.04'
  psVersion: 'pwsh'
  script: "$PSVersionTable | Out-String"
jobs:
  - job:
    displayName: "${{parameters.vmImage}} ${{parameters.psVersion}}"
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - ${{parameters.psVersion}}: ${{parameters.script}}
    - task: PublishCodeCoverageResults@1
      displayName: 'Capture Pester Code Coverage Result'
      inputs:
        summaryFileLocation: '**/CodeCoverage.xml'
        failIfCoverageEmpty: false
    - task: PublishTestResults@2
      displayName: 'Capture Pester Test Result'
      inputs:
        testRunner: 'NUnit'
        testRunTitle: 'Pester ${{parameters.vmImage)-${{parameters.psVersion}}'
        failTaskOnFailedTests: true
        #testResultsFiles: '**/TestResults.xml'
